name: TheWindowCalculator
description: A simple price and time estimator to aid the hard-working people in the window cleaning industry.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^7.1.5
  sqflite: ^1.3.0
  path_provider: ^1.6.24
  path: ^1.7.0
  image_picker: ^0.6.7+22
  flutter_picker: ^1.1.5
  common_tools:
    path: "D:/SoftwareDev/Libraries/FlutterLibraries/common_tools"
  shared_preferences: ^0.5.12+4
  soyhaha:
    path: "D:/SoftwareDev/Libraries/FlutterLibraries/items"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/construction_factor.png
    - assets/images/filthy_factor.png
    - assets/images/hazard_factor.png
    - assets/images/sided_factor.png
    - assets/images/na_image.png
    - assets/images/solar_panel.png
    - assets/images/french_window.png
    - assets/images/standard_window.png
    - assets/images/casement_window.png
    - assets/images/picture_window.png
    - assets/images/garden_window.png
    - assets/images/comm_window.png
    - assets/images/windwall.png
  # Splash Screen images
    - assets/ss_icon/app_icon_mdpi.png
    - assets/ss_icon/app_icon_hdpi.png
    - assets/ss_icon/app_icon_xhdpi.png
    - assets/ss_icon/app_icon_xxhdpi.png
    - assets/ss_icon/app_icon_xxhdpi.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
